language: node_js

notifications:
  email: false

node_js:
  - '8'

env:
  matrix:
    - PACKAGE=jsx-render

before_install:
  - npm install -g lerna

install:
  - lerna bootstrap

script:
  - lerna run test --scope $PACKAGE

# jobs:
#   include:
#     # Define the release stage that runs semantic-release
#     - stage: release
#       node_js: '8'
#       script: skip
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script:
#           - npm run-script semantic-release
#     - stage: post-release
#       node_js: '8'
#       script: skip
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script:
#           - echo 'post release'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
